services:
  portfolio-postgres-db:
    image: bitnami/postgresql:latest
    container_name: portfolio-postgres-db
    ports:
      - "${DATABASE_PORT}:5432"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=portfolio
      - POSTGRESQL_TIMEZONE=America/Sao_Paulo
    volumes:
      - db_volume:/bitnami/postgresql
    networks:
      - local-network

  portfolio-pg-admin:
    image: dpage/pgadmin4:latest
    container_name: portfolio-pg-admin
    depends_on:
      - portfolio-postgres-db
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - TZ=America/Sao_Paulo
    ports:
      - "8082:80"
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - local-network

  firebase-emulator:
    image: spine3/firebase-emulator
    container_name: firebase-emulator
    environment:
      - GCP_PROJECT=${GCP_PROJECT}
      - ENABLE_UI=true
    ports:
      - "9000:9000"
      - "8080:8080"
      - "4000:4000"
      - "9099:9099"
      - "8085:8085"
      - "5001:5001"
      - "9199:9199"
    stdin_open: true
    tty: true
    command:
      [
        "/bin/sh",
        "-c",
        "/entrypoint.sh && firebase emulators:start --import=/firebase/baseline-data",
      ]
    volumes:
      - ./baseline-data:/firebase/baseline-data
      - ./entrypoint.sh:/entrypoint.sh
    restart: always

  portfolio-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    volumes:
      - ./core:/app/core
      - ./database:/app/database
      - ./packages:/app/packages
      - ./web:/app/web
      - /app/node_modules
      - /app/core/node_modules
      - /app/database/node_modules
      - /app/packages/node_modules
      - /app/web/node_modules
    depends_on:
      - portfolio-postgres-db
      - firebase-emulator
    networks:
      - local-network

volumes:
  db_volume:

networks:
  local-network:
    driver: bridge