packages:
  - web
  - core
  - packages
  - database
  - assistant

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - '@prisma/engines'
  - '@scarf/scarf'
  - esbuild
  - prisma
