// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// NOTE: We intentionally avoid the Prisma `env()` helper here because it throws
// a PrismaConfigEnvError when DATABASE_URL is missing — even during `prisma generate`,
// which does not require a live database connection. Using process.env directly
// allows `generate` to succeed in CI without a real DATABASE_URL secret.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "pnpx tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env.DIRECT_DATABASE_URL ?? process.env.DATABASE_URL ?? "postgresql://placeholder:placeholder@localhost:5432/placeholder",
  },
});
