import type { TimelineMilestone } from "../timeline-data"

export const timelineMilestonesFixture: TimelineMilestone[] = [
  {
    slug: "fundacao-cms",
    kind: "milestone",
    dateLabelPt: "Jan – Fev 2026",
    dateLabelEn: "Jan – Feb 2026",
    titlePt: "A Fundação e o CMS",
    titleEn: "The Foundation and the CMS",
    impactPt: "Imaginei a cena: terminar um curso, mexer no código e publicar o site inteiro de novo só pra acrescentar um item numa lista.",
    impactEn: "I pictured the scene: finish a course, tweak the code, and publish the whole site again just to add one item to a list.",
    tags: ["Next.js", "PostgreSQL", "Prisma", "NextAuth", "Zod", "Turborepo"],
    narrationPt:
      "No começo eu só queria ter um portfólio online. Mas pensei bem: eu ia estar atualizando esse site toda semana, com projeto novo, certificado novo, e não queria ter que mexer no código toda vez só pra isso. Então, antes de qualquer coisa, construí um jeito de eu mesmo entrar no site e editar tudo sozinho, sem precisar programar de novo cada vez. Foi aí que esse portfólio deixou de ser só uma página parada e virou algo vivo, que eu podia atualizar na hora que quisesse.",
    narrationEn:
      "In the beginning, I just wanted an online portfolio. But I thought about it: I'd be updating this site every week, a new project here, a new certificate there, and I didn't want to touch the code every single time just for that. So, before anything else, I built a way to log in myself and edit everything on my own, without having to code it again each time. That's when this portfolio stopped being just a static page and became something alive, something I could update whenever I wanted.",
    problemPt: "No começo cheguei a cogitar um portfólio simples, só umas páginas estáticas.",
    problemEn: "At first I considered a simple portfolio, just a few static pages.",
    inflectionPt: "Não fui atrás de tecnologia nova só para parecer moderno no currículo.",
    inflectionEn: "I didn't chase new technology just to look modern on a resume.",
    solutionPt: "Construí uma base de monorepo com autenticação própria e um painel de controle simples.",
    solutionEn: "I built a monorepo foundation with my own authentication and a simple control panel.",
  },
  {
    slug: "batalha-midias",
    kind: "milestone",
    dateLabelPt: "Mar – Abr 2026",
    dateLabelEn: "Mar – Apr 2026",
    titlePt: "A Batalha das Mídias e do Deploy",
    titleEn: "The Media and Deploy Battle",
    impactPt: "A imagem simplesmente não aparecia, do nada, sem um padrão que desse pra entender.",
    impactEn: "The image would simply vanish, out of nowhere, with no pattern I could pin down.",
    tags: ["Vercel", "Server Actions", "Cloudinary", "SOLID"],
    narrationPt: "Depois de um tempo, comecei a notar um problema estranho nas fotos dos meus projetos.",
    narrationEn: "After a while, I started noticing a strange problem with the photos of my projects.",
    problemPt: "Comecei a notar imagens do carrossel de projetos que simplesmente não carregavam.",
    problemEn: "I started noticing project carousel images that simply wouldn't load.",
    inflectionPt: "Cheguei a um ponto em que continuar caçando esse bug fantasma não fazia mais sentido.",
    inflectionEn: "I reached a point where chasing that ghost bug no longer made sense.",
    solutionPt: "Tirei o Docker de produção de vez e passei a rodar direto na Vercel com Server Actions.",
    solutionEn: "I removed Docker from production for good and started running straight on Vercel with Server Actions.",
  },
  {
    slug: "hiato",
    kind: "gap",
    dateLabelPt: "Mai – Jul 2026",
    dateLabelEn: "May – Jul 2026",
    titlePt: "O Hiato",
    titleEn: "The Gap",
    impactPt: "Passei semanas sem tocar em uma linha de código, convencido de que o portfólio estava pronto.",
    impactEn: "I went weeks without touching a line of code, convinced the portfolio was done.",
    tags: [],
    narrationPt: "Depois de resolver aquilo, cheguei a achar que o portfólio estava pronto.",
    narrationEn: "After fixing that, I actually thought the portfolio was done.",
    problemPt: "Depois da correria pra resolver mídia e infraestrutura, cheguei a acreditar de verdade que o portfólio estava pronto.",
    problemEn: "After the rush to fix media and infrastructure, I truly believed the portfolio was done.",
    inflectionPt: "Não teve um estalo único, um bug que quebrou algo ou um evento específico.",
    inflectionEn: "There wasn't a single spark, a bug that broke something, or one specific event.",
    solutionPt: "A retomada veio em agosto, e não foi um retorno morno de quem só queria fechar umas pontas soltas.",
    solutionEn: "Work resumed in August, and it wasn't a lukewarm comeback from someone just wanting to tie up a few loose ends.",
  },
  {
    slug: "a-ideia",
    kind: "milestone",
    dateLabelPt: "Ago 2026",
    dateLabelEn: "Aug 2026",
    titlePt: "A Ideia",
    titleEn: "The Idea",
    impactPt: "Voltando do hiato, olhei pro site e pensei: isso ainda não parece meu.",
    impactEn: "Coming back from the gap, I looked at the site and thought: this still doesn't feel like me.",
    tags: ["Product Thinking", "IA", "Identidade Visual"],
    narrationPt: "Voltando depois desse tempo parado, olhei pro site e pensei: isso ainda não parece com quem eu sou.",
    narrationEn: "Coming back after that quiet stretch, I looked at the site and thought: this still doesn't feel like me.",
    problemPt: "O portfólio funcionava, mas continuava com a cara de qualquer outro portfólio.",
    problemEn: "The portfolio worked, but it still looked like any other portfolio.",
    inflectionPt: "Foi então que juntei duas ideias que vinham rondando minha cabeça separadas.",
    inflectionEn: "That's when I connected two ideas that had been circling separately in my head.",
    solutionPt: "Decidi tocar as duas coisas juntas.",
    solutionEn: "I decided to work on both at the same time.",
  },
  {
    slug: "era-ia-avatar",
    kind: "milestone",
    dateLabelPt: "Ago 2026",
    dateLabelEn: "Aug 2026",
    titlePt: "A Era da IA e o Pivô do Avatar",
    titleEn: "The AI Era and the Avatar Pivot",
    impactPt: "Testei o 3D, mas além de pesado, era complexo demais pra um portfólio pessoal.",
    impactEn: "I tried 3D, but besides being heavy, it was too complex for a personal portfolio.",
    tags: ["RAG", "pgvector", "Gemini", "Three.js", "SEO", "i18n"],
    narrationPt: "O assistente que eu tinha criado funcionava bem, mas parecia genérico.",
    narrationEn: "The assistant I had built worked fine, but it felt generic.",
    problemPt: "Voltei ao projeto com domínio próprio e SEO avançado no ar.",
    problemEn: "I came back to the project with my own domain and advanced SEO live.",
    inflectionPt: "Tentei resolver isso dando um rosto ao assistente.",
    inflectionEn: "I tried solving this by giving the assistant a face.",
    solutionPt: "A saída mais simples acabou sendo a certa: um personagem 2D inspirado nos avatares do Xbox 360.",
    solutionEn: "The simplest way out turned out to be the right one: a 2D character inspired by Xbox 360 avatars.",
    sequence: [
      {
        datePt: "25/08",
        dateEn: "Aug 25",
        labelPt: "VRM descartado → Three.js tentado e também descartado → pouso no sprite 2D, tudo no mesmo dia.",
        labelEn: "VRM discarded → Three.js tried and also discarded → landed on the 2D sprite, all in the same day.",
      },
    ],
    graveyard: [
      {
        titlePt: "Avatar 3D (VRM)",
        titleEn: "3D Avatar (VRM)",
        descriptionPt: "Primeira tentativa de dar um rosto ao assistente: um modelo 3D baseado em VRM.",
        descriptionEn: "First attempt to give the assistant a face: a 3D VRM-based model.",
      },
    ],
  },
  {
    slug: "refinamento",
    kind: "milestone",
    dateLabelPt: "Set 2026",
    dateLabelEn: "Sep 2026",
    titlePt: "Refinamento",
    titleEn: "Refinement",
    impactPt: "A conversa com o avatar ainda tinha arestas cruas.",
    impactEn: "The conversation with the avatar still had rough edges.",
    tags: ["UI polish", "Cursos", "Certificações"],
    narrationPt: "Com o visual e o assistente resolvidos, sobraram só alguns detalhes menores.",
    narrationEn: "With the look and the assistant settled, only a few smaller details were left.",
    problemPt: "Com a identidade visual e o avatar resolvidos, sobraram os detalhes menores, mas ainda incômodos.",
    problemEn: "With the visual identity and the avatar settled, what was left were smaller but still nagging details.",
    inflectionPt: "Separar essas duas categorias deixaria muito mais claro, num relance, o que é formação formal.",
    inflectionEn: "Separating these two categories would make it much clearer, at a glance, what's formal education.",
    solutionPt: "Em 01/09, refatorei a interface imersiva do diálogo pro formato visual novel completo.",
    solutionEn: "On 09/01, I refactored the immersive dialogue interface into the full visual novel format.",
  },
  {
    slug: "ideia-da-jornada",
    kind: "milestone",
    dateLabelPt: "Set 2026",
    dateLabelEn: "Sep 2026",
    titlePt: "A Ideia da Jornada",
    titleEn: "The Journey Idea",
    impactPt: "A professora chegou do meu lado numa aula de Arquitetura de Software e perguntou o que eu estava fazendo.",
    impactEn: "The professor walked up next to me during an Architecture of Software class and asked what I was working on.",
    tags: ["UX Writing", "Storytelling", "shadcn/ui Sheet"],
    narrationPt: "Com tudo isso pronto, achei que o portfólio estava, enfim, completo.",
    narrationEn: "With all of that done, I thought the portfolio was finally complete.",
    problemPt: "Com o Refinamento fechado, o portfólio estava tecnicamente completo.",
    problemEn: "With Refinement closed, the portfolio was technically complete.",
    inflectionPt: "Veio de um lugar totalmente despretensioso: numa aula de Arquitetura de Software.",
    inflectionEn: "It came from a completely unpretentious moment: in an Architecture of Software class.",
    solutionPt: "Nasceu essa seção de Jornada do Projeto.",
    solutionEn: "This Project Journey section was born.",
  },
]
